### ISSUE TITLE
Triggered re-evaluated submission should be marked differently

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Backend#311]
A submission which was triggered by an assistant appears in the version list like any other submission, but does not count towards the number of attempts (#268, #308).

We should show them differently

**Comment by Phhofm** [comment]
different naming: Automated Submission or Automated Evaluation. Otherwise it will be displayed like the other submissions. Careful testing that the students dont use a submission if the automated reevaluation gets triggered by the course owner. Also we should be careful about access to reevalution, that it cant be triggered by tutors, maybe only by course owner

**Comment by mech-studi** [comment]
Flag to identify automatically triggered submissions is isTriggeredReSubmission
